# Define at run time :
# user_name - always
# user_password - to define password
# user_authkey - to define authorized ssh key
# user_secured - to enforce security

- name: Manages system users
  hosts: "{{ ip_serveur }}"
  gather_facts: false
  
  vars:
    user_secured: false
    user_name: admintest
    user_password: admin1234
    user_homedir: /home/admintest
    
    
    
  tasks:
    - name: Ensure {{ user_name }} is present
      user:
        name: '{{ user_name }}'
        uid: '{{ user_uid | default(omit) }}'
        group: '{{ user_group | default(omit) }}'
        comment: '{{ user_comment | default(omit) }}'
        home: '{{ user_homedir | default(omit) }}'
        shell: '{{ user_shell | default(omit) }}'
        groups: '{{ user_groups | default(omit) }}'
      register: user_created
      when: user_name is defined
      
    - name: Set {{ user_name }} password
      user:
        name: '{{ user_name }}'
        password: '{{ user_password }}'
      when: 
        - user_name is defined
        - user_password is defined

    - block:
        - name: Ensure permissions are set on {{ user_name }} files
          file:
            path: '{{ item.path }}'
            mode: '{{ item.mode }}'
            owner: '{{ user_name }}'
            group: '{{ user_group | default(user_name) }}'
          with_items: '{{ files }}'
      rescue:
        - name: Ensure permissions are set on {{ user_name }} files
          file:
            path: '{{ item.path }}'
            mode: '{{ item.mode }}'
            owner: '{{ user_name }}'
            group: '{{ user_group | default(user_name) }}'
            state: touch
          with_items: '{{ files }}'
      vars:
        files:
          - path: '{{ user_homedir }}'
            mode: '0750'
          - path: '{{ user_homedir }}/.profile'
            mode: '0700'

