- name: Creating a new DC with my name
  hosts: mypc
  gather_facts: false
  
    
  tasks:
    - name: Creating a new DC with my name
      become: true
      win_shell: |
             Import-Module -Name VMware.PowerCLI
             Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -confirm:$false
             Connect-VIServer -Server 10.126.254.11 -User administrator@vsphere.local -Password admin1234
             New-Datacenter -Location (Get-Folder -NoRecursion) -Name JULIEN.PETIT
             New-Cluster -Location JULIEN.PETIT -Name STEVEN.PEDARD -HAEnabled
             New-VM -Name ROMARIC.TRAN -Host {{ esx }} -NumCpu {{ num_cpu }} -MemoryMB {{ num_memory }} -Datastore {{ datastore_name }}
